# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='server.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x11room_server.proto\".\n\x0b\x43ommonReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x11\n\terror_msg\x18\x02 \x01(\t\"E\n\rJoinRoomReply\x12\x1c\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x0c.CommonReply\x12\x16\n\x0egame_record_id\x18\x02 \x01(\x05\"8\n\x15RandomJoinRoomRequest\x12\x11\n\tplayer_id\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\x05\"p\n\x0fJoinRoomRequest\x12\x11\n\tplayer_id\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x13\n\x0broom_number\x18\x04 \x01(\x05\x12\x15\n\rneed_password\x18\x05 \x01(\x05\x12\x10\n\x08password\x18\x06 \x01(\x05\"g\n\x11\x43reateRoomRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x11\n\tscript_id\x18\x03 \x01(\x05\x12\x0c\n\x04lock\x18\x04 \x01(\x08\x12\x10\n\x08password\x18\x05 \x01(\t\"\'\n\x12RollOutRoomRequest\x12\x11\n\tplayer_id\x18\x02 \x01(\x05\"R\n\x12KicksPlayerRequest\x12\x11\n\tplayer_id\x18\x02 \x01(\x05\x12\x0f\n\x07room_id\x18\x03 \x01(\x05\x12\x18\n\x10target_player_id\x18\x04 \x01(\x05\x32\x94\x02\n\nRoomServer\x12:\n\x0eRandomJoinRoom\x12\x16.RandomJoinRoomRequest\x1a\x0e.JoinRoomReply\"\x00\x12.\n\x08JoinRoom\x12\x10.JoinRoomRequest\x1a\x0e.JoinRoomReply\"\x00\x12\x32\n\nCreateRoom\x12\x12.CreateRoomRequest\x1a\x0e.JoinRoomReply\"\x00\x12\x32\n\x0bRollOutRoom\x12\x13.RollOutRoomRequest\x1a\x0c.CommonReply\"\x00\x12\x32\n\x0bKicksPlayer\x12\x13.KicksPlayerRequest\x1a\x0c.CommonReply\"\x00\x62\x06proto3')
)

_COMMONREPLY = _descriptor.Descriptor(
    name='CommonReply',
    full_name='CommonReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='code', full_name='CommonReply.code', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='error_msg', full_name='CommonReply.error_msg', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=21,
    serialized_end=67,
)

_JOINROOMREPLY = _descriptor.Descriptor(
    name='JoinRoomReply',
    full_name='JoinRoomReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='common', full_name='JoinRoomReply.common', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='game_record_id', full_name='JoinRoomReply.game_record_id', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=69,
    serialized_end=138,
)

_RANDOMJOINROOMREQUEST = _descriptor.Descriptor(
    name='RandomJoinRoomRequest',
    full_name='RandomJoinRoomRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='player_id', full_name='RandomJoinRoomRequest.player_id', index=0,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='type', full_name='RandomJoinRoomRequest.type', index=1,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=140,
    serialized_end=196,
)

_JOINROOMREQUEST = _descriptor.Descriptor(
    name='JoinRoomRequest',
    full_name='JoinRoomRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='player_id', full_name='JoinRoomRequest.player_id', index=0,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='type', full_name='JoinRoomRequest.type', index=1,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='room_number', full_name='JoinRoomRequest.room_number', index=2,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='need_password', full_name='JoinRoomRequest.need_password', index=3,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='password', full_name='JoinRoomRequest.password', index=4,
            number=6, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=198,
    serialized_end=310,
)

_CREATEROOMREQUEST = _descriptor.Descriptor(
    name='CreateRoomRequest',
    full_name='CreateRoomRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='player_id', full_name='CreateRoomRequest.player_id', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='type', full_name='CreateRoomRequest.type', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='script_id', full_name='CreateRoomRequest.script_id', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='lock', full_name='CreateRoomRequest.lock', index=3,
            number=4, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='password', full_name='CreateRoomRequest.password', index=4,
            number=5, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=312,
    serialized_end=415,
)

_ROLLOUTROOMREQUEST = _descriptor.Descriptor(
    name='RollOutRoomRequest',
    full_name='RollOutRoomRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='player_id', full_name='RollOutRoomRequest.player_id', index=0,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=417,
    serialized_end=456,
)

_KICKSPLAYERREQUEST = _descriptor.Descriptor(
    name='KicksPlayerRequest',
    full_name='KicksPlayerRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='player_id', full_name='KicksPlayerRequest.player_id', index=0,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='room_id', full_name='KicksPlayerRequest.room_id', index=1,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='target_player_id', full_name='KicksPlayerRequest.target_player_id', index=2,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=458,
    serialized_end=540,
)

_JOINROOMREPLY.fields_by_name['common'].message_type = _COMMONREPLY
DESCRIPTOR.message_types_by_name['CommonReply'] = _COMMONREPLY
DESCRIPTOR.message_types_by_name['JoinRoomReply'] = _JOINROOMREPLY
DESCRIPTOR.message_types_by_name['RandomJoinRoomRequest'] = _RANDOMJOINROOMREQUEST
DESCRIPTOR.message_types_by_name['JoinRoomRequest'] = _JOINROOMREQUEST
DESCRIPTOR.message_types_by_name['CreateRoomRequest'] = _CREATEROOMREQUEST
DESCRIPTOR.message_types_by_name['RollOutRoomRequest'] = _ROLLOUTROOMREQUEST
DESCRIPTOR.message_types_by_name['KicksPlayerRequest'] = _KICKSPLAYERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonReply = _reflection.GeneratedProtocolMessageType('CommonReply', (_message.Message,), dict(
    DESCRIPTOR=_COMMONREPLY,
    __module__='room_server_pb2'
    # @@protoc_insertion_point(class_scope:CommonReply)
))
_sym_db.RegisterMessage(CommonReply)

JoinRoomReply = _reflection.GeneratedProtocolMessageType('JoinRoomReply', (_message.Message,), dict(
    DESCRIPTOR=_JOINROOMREPLY,
    __module__='room_server_pb2'
    # @@protoc_insertion_point(class_scope:JoinRoomReply)
))
_sym_db.RegisterMessage(JoinRoomReply)

RandomJoinRoomRequest = _reflection.GeneratedProtocolMessageType('RandomJoinRoomRequest', (_message.Message,), dict(
    DESCRIPTOR=_RANDOMJOINROOMREQUEST,
    __module__='room_server_pb2'
    # @@protoc_insertion_point(class_scope:RandomJoinRoomRequest)
))
_sym_db.RegisterMessage(RandomJoinRoomRequest)

JoinRoomRequest = _reflection.GeneratedProtocolMessageType('JoinRoomRequest', (_message.Message,), dict(
    DESCRIPTOR=_JOINROOMREQUEST,
    __module__='room_server_pb2'
    # @@protoc_insertion_point(class_scope:JoinRoomRequest)
))
_sym_db.RegisterMessage(JoinRoomRequest)

CreateRoomRequest = _reflection.GeneratedProtocolMessageType('CreateRoomRequest', (_message.Message,), dict(
    DESCRIPTOR=_CREATEROOMREQUEST,
    __module__='room_server_pb2'
    # @@protoc_insertion_point(class_scope:CreateRoomRequest)
))
_sym_db.RegisterMessage(CreateRoomRequest)

RollOutRoomRequest = _reflection.GeneratedProtocolMessageType('RollOutRoomRequest', (_message.Message,), dict(
    DESCRIPTOR=_ROLLOUTROOMREQUEST,
    __module__='room_server_pb2'
    # @@protoc_insertion_point(class_scope:RollOutRoomRequest)
))
_sym_db.RegisterMessage(RollOutRoomRequest)

KicksPlayerRequest = _reflection.GeneratedProtocolMessageType('KicksPlayerRequest', (_message.Message,), dict(
    DESCRIPTOR=_KICKSPLAYERREQUEST,
    __module__='room_server_pb2'
    # @@protoc_insertion_point(class_scope:KicksPlayerRequest)
))
_sym_db.RegisterMessage(KicksPlayerRequest)

_ROOMSERVER = _descriptor.ServiceDescriptor(
    name='RoomServer',
    full_name='RoomServer',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=543,
    serialized_end=819,
    methods=[
        _descriptor.MethodDescriptor(
            name='RandomJoinRoom',
            full_name='RoomServer.RandomJoinRoom',
            index=0,
            containing_service=None,
            input_type=_RANDOMJOINROOMREQUEST,
            output_type=_JOINROOMREPLY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='JoinRoom',
            full_name='RoomServer.JoinRoom',
            index=1,
            containing_service=None,
            input_type=_JOINROOMREQUEST,
            output_type=_JOINROOMREPLY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='CreateRoom',
            full_name='RoomServer.CreateRoom',
            index=2,
            containing_service=None,
            input_type=_CREATEROOMREQUEST,
            output_type=_JOINROOMREPLY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='RollOutRoom',
            full_name='RoomServer.RollOutRoom',
            index=3,
            containing_service=None,
            input_type=_ROLLOUTROOMREQUEST,
            output_type=_COMMONREPLY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='KicksPlayer',
            full_name='RoomServer.KicksPlayer',
            index=4,
            containing_service=None,
            input_type=_KICKSPLAYERREQUEST,
            output_type=_COMMONREPLY,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_ROOMSERVER)

DESCRIPTOR.services_by_name['RoomServer'] = _ROOMSERVER

# @@protoc_insertion_point(module_scope)
