# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import microservice_invoke.room_proto.room_server_pb2 as room__server__pb2
from grpc_microservice.zk_minoter.grpc_decorate import proxy_grpc_func, register_module


class RoomServerStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.RandomJoinRoom = channel.unary_unary(
            '/RoomServer/RandomJoinRoom',
            request_serializer=room__server__pb2.RandomJoinRoomRequest.SerializeToString,
            response_deserializer=room__server__pb2.JoinRoomReply.FromString,
        )
        self.JoinRoom = channel.unary_unary(
            '/RoomServer/JoinRoom',
            request_serializer=room__server__pb2.JoinRoomRequest.SerializeToString,
            response_deserializer=room__server__pb2.JoinRoomReply.FromString,
        )
        self.CreateRoom = channel.unary_unary(
            '/RoomServer/CreateRoom',
            request_serializer=room__server__pb2.CreateRoomRequest.SerializeToString,
            response_deserializer=room__server__pb2.JoinRoomReply.FromString,
        )
        self.RollOutRoom = channel.unary_unary(
            '/RoomServer/RollOutRoom',
            request_serializer=room__server__pb2.RollOutRoomRequest.SerializeToString,
            response_deserializer=room__server__pb2.CommonReply.FromString,
        )
        self.KicksPlayer = channel.unary_unary(
            '/RoomServer/KicksPlayer',
            request_serializer=room__server__pb2.KicksPlayerRequest.SerializeToString,
            response_deserializer=room__server__pb2.CommonReply.FromString,
        )


class RoomServerStubProxy(object):
    server_class = RoomServerStub
    module_name = 'RoomServer'

    def __init__(self) -> None:
        super().__init__()

    @proxy_grpc_func(server_class, module_name)
    def RandomJoinRoom(self, req, **kwargs):
        pass

    @proxy_grpc_func(server_class, module_name)
    def JoinRoom(self, req, **kwargs):
        pass

    @proxy_grpc_func(server_class, module_name)
    def CreateRoom(self, req, **kwargs):
        pass

    @proxy_grpc_func(server_class, module_name)
    def RollOutRoom(self, req, **kwargs):
        pass

    @proxy_grpc_func(server_class, module_name)
    def KicksPlayer(self, req, **kwargs):
        pass


class RoomServerServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def RandomJoinRoom(self, request, context):
        """随机加入房间
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinRoom(self, request, context):
        """加入房间
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoom(self, request, context):
        """创建房间
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollOutRoom(self, request, context):
        """退出房间，只有code码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KicksPlayer(self, request, context):
        """房主踢人
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'RandomJoinRoom': grpc.unary_unary_rpc_method_handler(
            servicer.RandomJoinRoom,
            request_deserializer=room__server__pb2.RandomJoinRoomRequest.FromString,
            response_serializer=room__server__pb2.JoinRoomReply.SerializeToString,
        ),
        'JoinRoom': grpc.unary_unary_rpc_method_handler(
            servicer.JoinRoom,
            request_deserializer=room__server__pb2.JoinRoomRequest.FromString,
            response_serializer=room__server__pb2.JoinRoomReply.SerializeToString,
        ),
        'CreateRoom': grpc.unary_unary_rpc_method_handler(
            servicer.CreateRoom,
            request_deserializer=room__server__pb2.CreateRoomRequest.FromString,
            response_serializer=room__server__pb2.JoinRoomReply.SerializeToString,
        ),
        'RollOutRoom': grpc.unary_unary_rpc_method_handler(
            servicer.RollOutRoom,
            request_deserializer=room__server__pb2.RollOutRoomRequest.FromString,
            response_serializer=room__server__pb2.CommonReply.SerializeToString,
        ),
        'KicksPlayer': grpc.unary_unary_rpc_method_handler(
            servicer.KicksPlayer,
            request_deserializer=room__server__pb2.KicksPlayerRequest.FromString,
            response_serializer=room__server__pb2.CommonReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'RoomServer', rpc_method_handlers)
    register_module(generic_handler)
    server.add_generic_rpc_handlers((generic_handler,))
